### ISSUE TITLE
plugin-markdown: Support for JS examples

### ISSUE THREAD

**Issue by tadatuta** [agrarium/agrarium#27]
There are two types of examples in markdown docs:
1. BEMJSON which should be converted into iframe (implemented)
2. plain JS which should be kept as is

There's an agreement that second type of examples are marked with \```javascript instead of \```js

**Comment by awinogradov** [comment]
I think u mean this https://github.com/agrarium/agrarium/blob/master/packages/example-bem-site/example-bem-site.js#L38 ;) We support custom langs to catch from md and custom function to prepare inline examples.
